# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - bioc-release
  - bioc-devel

r_check_args: --no-build-vignettes
disable_homebrew: true
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
