# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-release
  - bioc-devel
sudo: false
cache: packages
os:
  - linux
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
